version: '3'

services:
  
  react:
    container_name: react
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env

  express:
    container_name: express
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - $EXPRESS_LOCAL_PORT:$EXPRESS_DOCKER_PORT
    volumes:
      - ./server:/app
      - ./server/storage:/app/storage
      - /app/node_modules
    env_file:
      - .env