version: '3'

services:
  
  react:
    container_name: react
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env

  express:
    container_name: express
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - $EXPRESS_LOCAL_PORT:$EXPRESS_DOCKER_PORT
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_ROOT_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_ROOT_USER_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./tmp/db:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - $MONGOEXPRESS_LOCAL_PORT:$MONGOEXPRESS_DOCKER_PORT
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=$MONGODB_DATABASE
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGODB_ROOT_USER
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGODB_ROOT_USER_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGODB_BASIC_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGODB_BASIC_USER_PASSWORD
    depends_on:
      - mongo 