services:
  - type: web
    name: user-feedback-app-server
    repo: https://github.com/pavelihno/user-feedback-app.git
    branch: cloud-deployment
    region: frankfurt
    plan: free
    env: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: development
      - key: EXPRESS_DOCKER_PORT
        value: 8080
      - key: EXPRESS_LOCAL_PORT
        value: 8080
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_PERIOD
        value: 1d
    - type: web
      name: user-feedback-app-client
      repo: https://github.com/pavelihno/user-feedback-app.git
      branch: cloud-deployment
      region: frankfurt
      plan: free
      env: docker
      rootDir: client
      dockerfilePath: ./Dockerfile
      numInstances: 1
      healthCheckPath: /
      envVars:
        - key: REACT_APP
          value: true
        - key: NODE_ENV
          value: development
        - key: REACT_APP_SERVER_URL
          value: https://user-feedback-app-server.onrender.com
        - key: REACT_DOCKER_PORT
          value: 3000
        - key: REACT_LOCAL_PORT
          value: 3000
